name: Assign Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/assign'
    steps:
    - name: Assign issue to commenter
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.payload.issue.number;
          const commenter = context.payload.comment.user.login;

          // Assign the issue to the commenter
          await github.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            assignees: [commenter]
          });